unbind r
bind r source-file ~/.tmux.conf

set-option -g focus-events on

set -g prefix C-s

set -g base-index 1
setw -g pane-base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -a terminal-features 'xterm-256color:RGB'
